
@host=http://localhost:8080
@authorization=Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoianRvcnJlczk5MEBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjU2MzQ4ODk4LCJleHAiOjE2NTY0MzUyOTh9.wf3R16gJP6FBxg3NQ06SG3E98wsUDlOqTIV3yWxAwLWEqgr9-d4RyqSs1hWcIm_n8PfRC4nE0vSYBTb6sAT0cQ

###
POST http://localhost:8080/users/sign-up
Content-Type: application/json

{
    "firstname": "julio",
    "lastname": "torres",
    "email": "jtorres990@gmail.com",
    "phone": "3013819315",
    "password": "12345678"
}

###
POST http://localhost:8080/users/sign-in
Content-Type: application/json
Accept: application/json

{
    "email": "jtorres990@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:8080/users/session
Authorization: {{authorization}}
Content-Type: application/json
Accept: application/json


###
GET {{host}}/home

###
GET {{host}}/banks
Content-Type: application/json
Authorization: {{authorization}}

###
POST {{host}}/banks
Content-Type: application/json
Authorization: {{authorization}}

{
    "name": "bancolombia"
}

###
POST {{host}}/banks
Content-Type: application/json
Authorization: {{authorization}}

{
    "name": "credibanco"
}

###
PATCH {{host}}/banks/9
Content-Type: application/json
Authorization: {{authorization}}

{
    "name": "Bancolombia"
}

###
POST {{host}}/me/assignToBank
Content-Type: application/json
Authorization: {{authorization}}

{
    "id": 9
}

###
GET {{host}}/me/banks
Content-Type: application/json
Authorization: {{authorization}}

###
GET {{host}}/me/debts
Content-Type: application/json
Authorization: {{authorization}}

###
POST {{host}}/me/createDebts
Authorization: {{authorization}}
Content-Type: application/json

{
    "bankId": 9,
    "amount": 1000000,
    "dues": 12,
    "concept": "Lavadora"
}

###
GET {{host}}/me/debts
Content-Type: application/json
Authorization: {{authorization}}

###
POST {{host}}/me/payFee
Authorization: {{authorization}}
Content-Type: application/json

{
    "id": 15,
    "amount": 90259
}